spring:
  application:
    name: demo-api
    version: 1.0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/demo_app
    username: postgres
    password: password
    hikari:
      max-lifetime: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  api-version: v1
  module-name: "Mobile Banking"
  key-store: /opt/demo/keystore.pfx
  key-alias: demo
  key-store-password: 'changeit'
  token-expiration: 60
  auth-whitelist:
    - "/api/auth/**"
    - "/v3/api-docs/**"
    - "/v3/api-docs.yaml"
    - "/swagger-ui/**"

